### ISSUE TITLE
Пожалуйста, дайте прямую ссылку на .apk для тех, у кого нет google play на девайсе

### ISSUE THREAD

**Issue by vovkav** [eprst/KTodo#1]
Пожалуйста, дайте прямую ссылку на .apПожалуйста, дайте прямую ссылку на .apk для тех, у кого нет google play на девайсе для тех, у кого нет google play на девайсе

**Comment by IzzySoft** [comment]
Maybe you could attach it to the [releases](https://github.com/eprst/KTodo/releases) whenever you release a new version? Above version is quite "stariy" so to speak (sorry, no cyrillic keyboard at the moment :)

**Comment by eprst** [comment]
will do in a day or two

**Comment by eprst** [comment]
готово
https://github.com/eprst/KTodo/releases

**Comment by IzzySoft** [comment]
Spasibo bolschoje!
